name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop
    tags:
      - v*

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set tag names
        id: tag_names
        run: |
          echo "GITHUB_EVENT_NAME                         =" "${GITHUB_EVENT_NAME}"
          echo "git branch --show-current | sed 's|/|-|g' =" $(git branch --show-current | sed 's|/|-|g')
          echo "git rev-parse --short HEAD                =" $(git rev-parse --short HEAD)
          echo "git describe --tags --always              =" $(git describe --tags --always)
          echo "GITHUB_REF#refs/heads/                    =" "${GITHUB_REF#refs/heads/}"
          echo "GITHUB_HEAD_REF#refs/heads/               =" "${GITHUB_HEAD_REF#refs/heads/}"
          echo "GITHUB_BASE_REF#refs/heads/               =" "${GITHUB_BASE_REF#refs/heads/}"

